# syntax=docker/dockerfile:1

FROM golang:1.22.1

# Set destination for COPY
WORKDIR /app

RUN go install github.com/cosmtrek/air@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

EXPOSE 3000