FROM golang:1.22.1 as env

WORKDIR /app

RUN go install github.com/air-verse/air@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./

RUN go mod download
RUN go mod tidy
RUN go mod vendor

COPY *.go ./

EXPOSE 3000

ENTRYPOINT [ "air" ]


FROM golang:1.22.1 as prod

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /server ./cmd/server

EXPOSE 3000

CMD [ "/server" ]