FROM golang:1.22.1

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./

RUN go mod download
RUN go mod vendor

COPY *.go ./

EXPOSE 3000

ENTRYPOINT [ "air" ]